// electron/trtexecShim.ts
//
// vsmlrt.py's TensorRT backend builds engines at runtime by shelling out to
// trtexec — a binary the TensorRT pip wheels don't ship. This writes a tiny
// launcher at PATHS.TRTEXEC_SHIM that forwards trtexec-style arguments to the
// app's own Python API builder (include/build_trt_engine.py, the same one the
// model importer uses), which understands that argument vocabulary and reports
// progress through the [vk-build] protocol. Generated scripts set
// vsmlrt.trtexec_path to this shim (see scriptGenerator.generateBackendHelper).
//
// vsmlrt spawns trtexec with a nearly empty environment (`{"CUDA_MODULE_LOADING":
// "LAZY"}` plus the backend's custom_env), so the shim restores the minimum
// Windows needs to start cmd.exe and Python.

import * as path from 'path';
import * as fs from 'fs-extra';
import { logger } from './logger';
import { IS_WINDOWS, PATHS } from './constants';
import { getBundledBasePath } from './utils';

/** Windows fallback when SystemRoot is missing from the app's own environment. */
const DEFAULT_SYSTEM_ROOT = 'C:\\Windows';

export function getSystemRoot(): string {
  return process.env.SystemRoot || process.env.SYSTEMROOT || DEFAULT_SYSTEM_ROOT;
}

/**
 * Copies the bundled engine builder next to the app data folder and (re)writes
 * the trtexec shim that runs it. Cheap enough to call on every launch, which
 * also keeps both files in step with an upgraded app bundle.
 *
 * Returns the shim path.
 */
export async function ensureTrtexecShim(): Promise<string> {
  const bundledBuilder = path.join(getBundledBasePath(), 'include', 'build_trt_engine.py');
  const builderScript = path.join(PATHS.APP_DATA, 'build_trt_engine.py');

  await fs.ensureDir(PATHS.APP_DATA);
  await fs.copy(bundledBuilder, builderScript, { overwrite: true });

  const lines = IS_WINDOWS
    ? buildWindowsShim(builderScript)
    : buildPosixShim(builderScript);

  await fs.writeFile(PATHS.TRTEXEC_SHIM, lines.join(IS_WINDOWS ? '\r\n' : '\n'), 'utf-8');
  if (!IS_WINDOWS) {
    await fs.chmod(PATHS.TRTEXEC_SHIM, 0o755);
  }

  logger.info(`trtexec shim ready: ${PATHS.TRTEXEC_SHIM}`);
  return PATHS.TRTEXEC_SHIM;
}

// ASCII only: the .cmd is read by cmd.exe under whatever codepage is active.
function buildWindowsShim(builderScript: string): string[] {
  const systemRoot = getSystemRoot();
  return [
    '@echo off',
    'rem Generated by Vapourkit - do not edit, this file is rewritten at launch.',
    'rem vsmlrt.py spawns trtexec to build TensorRT engines; the TensorRT pip',
    'rem wheels ship no trtexec, so the arguments go to Vapourkit\'s Python API',
    'rem builder instead. The env vsmlrt hands us is nearly empty, hence the',
    'rem SystemRoot/PATH restore below. cmd exits with the last command\'s exit',
    'rem code, which is what vsmlrt checks.',
    `set "SystemRoot=${systemRoot}"`,
    `set "PATH=${systemRoot}\\System32;${path.dirname(PATHS.PYTHON)}"`,
    `"${PATHS.PYTHON}" -u "${builderScript}" %*`,
    '',
  ];
}

function buildPosixShim(builderScript: string): string[] {
  return [
    '#!/bin/sh',
    '# Generated by Vapourkit - do not edit, this file is rewritten at launch.',
    '# Forwards vsmlrt.py\'s trtexec-style engine build arguments to Vapourkit\'s',
    '# Python API builder (the TensorRT pip wheels ship no trtexec binary).',
    `exec "${PATHS.PYTHON}" -u "${builderScript}" "$@"`,
    '',
  ];
}
