/**
 * Regenerates electron/scriptSourceManifest.ts: for each source of the Python
 * modules in vs-scripts, its version and the sha256 of every file it installs.
 *
 * Launch compares an install's vs-scripts against this without downloading or
 * extracting anything, so an update that changed no script costs nothing, and
 * one that did replaces exactly the files it changed. Rerun whenever
 * HYBRID_SCRIPTS_COMMIT or an archive in include/scripts changes; a test holds
 * the manifest to both.
 *
 *   npx tsx scripts/generateScriptManifest.ts
 *
 * Needs network access for the Hybrid scripts download.
 */
import { execFileSync } from 'child_process';
import * as crypto from 'crypto';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import {
  BUNDLED_SCRIPT_ARCHIVES,
  HYBRID_SCRIPTS_COMMIT,
  HYBRID_SCRIPTS_SOURCE,
  HYBRID_SCRIPTS_URL,
  isSupersededScript,
  type ScriptSourceManifestEntry,
} from '../electron/scriptSources';
import { hybridScriptFiles, listFilesRecursive } from '../electron/scriptFiles';

const repoRoot = path.resolve(__dirname, '..');
const outputPath = path.join(repoRoot, 'electron', 'scriptSourceManifest.ts');
const sevenZip = path.join(repoRoot, 'node_modules', '7zip-bin', 'win', 'x64', '7za.exe');

const sha256 = (buffer: Buffer) => crypto.createHash('sha256').update(buffer).digest('hex');

function extract(archive: string, into: string): void {
  execFileSync(process.platform === 'win32' ? sevenZip : '7z', ['x', archive, `-o${into}`, '-y'], { stdio: 'ignore' });
}

async function main(): Promise<void> {
  const work = fs.mkdtempSync(path.join(os.tmpdir(), 'vk-script-manifest-'));
  const manifest: Record<string, ScriptSourceManifestEntry> = {};
  try {
    const response = await fetch(HYBRID_SCRIPTS_URL);
    if (!response.ok) throw new Error(`Hybrid scripts download failed: HTTP ${response.status}`);
    const zip = path.join(work, 'hybrid.zip');
    fs.writeFileSync(zip, Buffer.from(await response.arrayBuffer()));
    extract(zip, path.join(work, 'hybrid'));
    const hybrid: Record<string, string> = {};
    for (const [name, fullPath] of await hybridScriptFiles(path.join(work, 'hybrid'))) {
      if (isSupersededScript(name)) continue;
      hybrid[name] = sha256(fs.readFileSync(fullPath));
    }
    manifest[HYBRID_SCRIPTS_SOURCE] = { version: HYBRID_SCRIPTS_COMMIT, files: hybrid };

    for (const archive of BUNDLED_SCRIPT_ARCHIVES) {
      const archivePath = path.join(repoRoot, 'include', 'scripts', archive);
      const into = path.join(work, archive);
      extract(archivePath, into);
      const files: Record<string, string> = {};
      for (const relative of await listFilesRecursive(into)) {
        if (isSupersededScript(relative)) continue;
        files[relative] = sha256(fs.readFileSync(path.join(into, relative)));
      }
      manifest[archive] = { version: sha256(fs.readFileSync(archivePath)), files };
    }
  } finally {
    fs.rmSync(work, { recursive: true, force: true });
  }

  const body = Object.keys(manifest).sort().map(source => {
    const entry = manifest[source];
    const files = Object.keys(entry.files).sort()
      .map(file => `      ${JSON.stringify(file)}: '${entry.files[file]}',`).join('\n');
    return `  ${JSON.stringify(source)}: {\n    version: '${entry.version}',\n    files: {\n${files}\n    },\n  },`;
  }).join('\n');

  fs.writeFileSync(outputPath, `// Generated by scripts/generateScriptManifest.ts - do not edit by hand.
// Every file each vs-scripts source installs, at the version this app ships.
import type { ScriptSourceManifestEntry } from './scriptSources';

export const SCRIPT_SOURCE_MANIFEST: Readonly<Record<string, ScriptSourceManifestEntry>> = {
${body}
};
`);
  for (const [source, entry] of Object.entries(manifest)) {
    console.log(`${source}: ${Object.keys(entry.files).length} files at ${entry.version.slice(0, 12)}`);
  }
}

main().catch(error => {
  console.error(error);
  process.exit(1);
});
